### ISSUE TITLE
can't compile :(

### ISSUE THREAD

**Issue by grisun0** [MatheuZSecurity/KThreadShell#1]
Hello bro , can hel me, i trying to compile, but ton working :(

make -C /lib/modules/6.5.0-27-generic/build M=/root modules
make[1]: Entering directory '/usr/lib/modules/6.5.0-27-generic/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.5.0-27-generic/build'
make: *** [Makefile:4: all] Error 2
make -C /lib/modules/6.5.0-27-generic/build M=/root clean
make[1]: Entering directory '/usr/lib/modules/6.5.0-27-generic/build'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.5.0-27-generic/build'
make: *** [Makefile:7: clean] Error 2

Makefile:
obj-m += rock.o

all:
        make -C /lib/modules/6.5.0-27-generic/build M=$(PWD) modules

clean:
        make -C /lib/modules/6.5.0-27-generic/build M=$(PWD) clean

**Comment by MatheuZSecurity** [comment]
> Hello bro , can hel me, i trying to compile, but ton working :(
> 
> make -C /lib/modules/6.5.0-27-generic/build M=/root modules make[1]: Entering directory '/usr/lib/modules/6.5.0-27-generic/build' make[1]: *** No rule to make target 'modules'. Stop. make[1]: Leaving directory '/usr/lib/modules/6.5.0-27-generic/build' make: *** [Makefile:4: all] Error 2 make -C /lib/modules/6.5.0-27-generic/build M=/root clean make[1]: Entering directory '/usr/lib/modules/6.5.0-27-generic/build' make[1]: *** No rule to make target 'clean'. Stop. make[1]: Leaving directory '/usr/lib/modules/6.5.0-27-generic/build' make: *** [Makefile:7: clean] Error 2
> 
> Makefile: obj-m += rock.o
> 
> all: make -C /lib/modules/6.5.0-27-generic/build M=$(PWD) modules
> 
> clean: make -C /lib/modules/6.5.0-27-generic/build M=$(PWD) clean

rock.o??? Your makefile is incorrect, I am using kernel 6.10.9-amd64 and on previous kernels it is also compiling and loading correctly, there is nothing wrong with compiling with KthreadShell.

![kthreadshell](https://github.com/user-attachments/assets/c872e84a-0470-44d9-a640-269ef08d3410)
